name: Run PyTest, Build Dockerfile, & check for Docker vulnerability
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  pytest:
    name: PyTest Framework - Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Set up Python 3.14
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
        with:
          python-version: 3.14

      - name: Install dependencies for testing
        run: |
          python -m pip install --root-user-action ignore --upgrade pip
          pip install --root-user-action ignore -r requirements.txt
          pip install --root-user-action ignore -r test_requirements.txt

      - name: Test with PyTest
        run: pytest --html=tests/Report.html --self-contained-html

      - name: PyTest Report Generation
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        if: success() || failure()
        with:
          name: Pytest_Report           # Name of the folder
          path: tests/Report.html           # Path to test results
  docker_build:
    needs: pytest
    name: Build, Test, & Publish Development Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
    - name: Build image from Dockerfile
      run: docker build -t docker.io/crystalenvt/movarr:${{ github.sha }} .

    - name: Run Trivy vulnerability scanner against built image
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
      with:
        image-ref: 'docker.io/crystalenvt/movarr:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Log in to Docker Hub
      uses: docker/login-action@28fdb31ff34708d19615a74d67103ddc2ea9725c
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051
      with:
        images: crystalenvt/movarr

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@9e436ba9f2d7bcd1d038c8e55d039d37896ddc5d
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: crystalenvt/movarr:${{ env.BRANCH_NAME }},crystalenvt/movarr:${{ env.BRANCH_NAME }}-${{ github.sha }}