name: Build and release Docker images
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          fetch-depth: 1

      - name: Build Docker image
        uses: flownative/action-docker-build@master
        with:
          tag_ref: ${{ github.ref }}
          image_name: flownative/docker-base/base
          registry_password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release to docker.io
        uses: flownative/action-docker-publish-semver@master
        with:
          tag_ref: ${{ github.ref }}
          tag_latest: 'yes'

          source_image_name: docker.pkg.github.com/flownative/docker-base/base
          source_registry_username: github
          source_registry_password: ${{ secrets.GITHUB_TOKEN }}
          source_registry_endpoint: https://docker.pkg.github.com/v2/

          target_image_name: flownative/base
          target_registry_username: ${{ vars.DOCKERHUB_USERNAME }}
          target_registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
          target_registry_endpoint: https://index.docker.io/v1/
